# Generated by Django 4.2.7 on 2024-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignexam_category_categorys_class_name_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
